apiVersion: v1
kind: ConfigMap
metadata:
  name: stock-config
data:
  db-hostname: postgres
  db-port: "5432"
  db-name: stock_db
  region: apac
---
apiVersion: v1
kind: Secret
metadata:
  name: stock-secrets
type: Opaque
stringData:
  db-username: admin
  db-password: admin
  api-key: your_alpha_vantage_key
  sender-email: your_email@gmail.com
  sender-password: your_app_password
